# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "new-extenstion"
client_id = "a932177b269409ec57f5b6cb14ff7740"
application_url = "https://static-poison-hope-opposition.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://static-poison-hope-opposition.trycloudflare.com/auth/callback",
  "https://static-poison-hope-opposition.trycloudflare.com/auth/shopify/callback",
  "https://static-poison-hope-opposition.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "palani-dev.myshopify.com"
